In [2]:
import numpy as np


---
# A zoo of matrices
---


In [4]:

# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(R)

# identity
I = np.eye(3)
print(I)

# zeros
Z = np.zeros((4,4))
print(Z)

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D)

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L)

# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(4,4)
# C = np.concatenate((A,B),axis=1) will throw error


[[-1.14291328 -0.70530886]
 [ 0.67088309  0.77880209]
 [ 0.58648341 -0.06023937]
 [ 1.09600777 -0.22120008]
 [ 0.4077221   0.73145808]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
[[ 0.34259322  0.          0.          0.          0.        ]
 [ 0.3561811   0.95188896  0.          0.          0.        ]
 [-0.1107864   0.36647306 -0.85699729  0.          0.        ]
 [-1.56635924 -0.35743004  0.07784045 -0.85046524  0.        ]
 [-1.0006429   0.51736177 -0.51034357  0.35024005  0.26784983]]



---
# Matrix addition and subtraction
---


In [6]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
# A+B error
print(A+C)



# "shifting" a matrix
l = .3 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(Ds)

[[ 1.4131029   1.1490546  -0.46056944  0.9670408 ]
 [-0.32951446  0.57652174  0.33869653 -1.57450039]
 [-0.27424678  0.10633889 -1.04004326  0.21649758]
 [-0.08803414  1.72050671 -0.87288693 -0.97315647]
 [ 1.55522884  1.10437511 -0.18402481  0.48328796]]
[[ 0.8382016  -0.14572662  0.70059066 -0.47865948  0.0119868 ]
 [-1.72371584  0.43874911 -0.86287002  2.11227992 -0.83613073]
 [-0.54524315  1.32124201  0.23058934 -0.67350721 -0.39217302]
 [-0.29758952  1.08606993 -0.54963889 -0.64586969  0.28200647]
 [ 0.05526685 -2.04604797 -0.22253586 -0.20547069 -0.04642588]]



---
# Matrix-scalar multiplication
---


In [7]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]



---
# Diagonal and trace
---


In [8]:

M = np.round( 5*np.random.randn(4,4) )

# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr)
print(tr2)

[ 2. 10. -6. -6.]
[[ 2.  0.  0.  0.]
 [ 0. 10.  0.  0.]
 [ 0.  0. -6.  0.]
 [ 0.  0.  0. -6.]]
0.0
0.0
